version: '3.0'
services:
  demo-mongo-keys:
    image: openssl
    build: openssl/.
    volumes:
      - 'demo-mongo-keys:/mongo-conf'
    command: bash -c "openssl rand -base64 741 > /mongo-conf/mongodb-keyfile; chmod 600 /mongo-conf/mongodb-keyfile; chown 999 /mongo-conf/mongodb-keyfile"
  
  demo-mongo-primary:
    image: 'mongo:latest'
    volumes:
      - 'demo-mongo-keys:/opt/keyfile'
      - 'demo-mongo-data-0:/data/db'
    env_file: ./mongod.env
    ports:
      - '2717:27017'
    command: mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet demo-replica-set
    depends_on:
      - demo-mongo-keys
    networks:
      demo-replica-set:

  demo-mongo-node-1:
    image: 'mongo:latest'
    volumes:
      - 'demo-mongo-keys:/opt/keyfile'
      - 'demo-mongo-data-1:/data/db'
    env_file: ./mongod.env
    ports:
      - '27018:27017'
    command: mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet demo-replica-set
    depends_on:
      - demo-mongo-keys
    networks:
      demo-replica-set:

  demo-mongo-node-2:
    image: 'mongo:latest'
    volumes:
      - 'demo-mongo-keys:/opt/keyfile'
      - 'demo-mongo-data-2:/data/db'
    env_file: ./mongod.env
    ports:
      - '27019:27017'
    command: mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet demo-replica-set
    depends_on:
      - demo-mongo-keys
    networks:
      demo-replica-set:

  demo-mongo-node-3:
    image: 'mongo:latest'
    volumes:
      - 'demo-mongo-keys:/opt/keyfile'
      - 'demo-mongo-data-3:/data/db'
    env_file: ./mongod.env
    ports:
      - '27020:27017'
    command: mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet demo-replica-set
    depends_on:
      - demo-mongo-keys
    networks:
      demo-replica-set:

volumes:
  demo-mongo-keys: 
  demo-mongo-data-0: 
  demo-mongo-data-1: 
  demo-mongo-data-2: 
  demo-mongo-data-3: 

networks:
  demo-replica-set:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.99.0/24
